// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// HLS_MACC_PERIPH_BUS
// 0x0000 : Control signals
//          bit 0  - ap_start (Read/Write/COH)
//          bit 1  - ap_done (Read/COR)
//          bit 2  - ap_idle (Read)
//          bit 3  - ap_ready (Read)
//          bit 7  - auto_restart (Read/Write)
//          others - reserved
// 0x0004 : Global Interrupt Enable Register
//          bit 0  - Global Interrupt Enable (Read/Write)
//          others - reserved
// 0x0008 : IP Interrupt Enable Register (Read/Write)
//          bit 0  - Channel 0 (ap_done)
//          bit 1  - Channel 1 (ap_ready)
//          others - reserved
// 0x000c : IP Interrupt Status Register (Read/TOW)
//          bit 0  - Channel 0 (ap_done)
//          bit 1  - Channel 1 (ap_ready)
//          others - reserved
// 0x3000 : Data signal of result
//          bit 31~0 - result[31:0] (Read)
// 0x3004 : Control signal of result
//          bit 0  - result_ap_vld (Read/COR)
//          others - reserved
// 0x1000 ~
// 0x1fff : Memory 'mean_image' (784 * 32b)
//          Word n : bit [31:0] - mean_image[n]
// 0x2000 ~
// 0x2fff : Memory 'input_image' (784 * 32b)
//          Word n : bit [31:0] - input_image[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XNEURAL_NET_HLS_MACC_PERIPH_BUS_ADDR_AP_CTRL          0x0000
#define XNEURAL_NET_HLS_MACC_PERIPH_BUS_ADDR_GIE              0x0004
#define XNEURAL_NET_HLS_MACC_PERIPH_BUS_ADDR_IER              0x0008
#define XNEURAL_NET_HLS_MACC_PERIPH_BUS_ADDR_ISR              0x000c
#define XNEURAL_NET_HLS_MACC_PERIPH_BUS_ADDR_RESULT_DATA      0x3000
#define XNEURAL_NET_HLS_MACC_PERIPH_BUS_BITS_RESULT_DATA      32
#define XNEURAL_NET_HLS_MACC_PERIPH_BUS_ADDR_RESULT_CTRL      0x3004
#define XNEURAL_NET_HLS_MACC_PERIPH_BUS_ADDR_MEAN_IMAGE_BASE  0x1000
#define XNEURAL_NET_HLS_MACC_PERIPH_BUS_ADDR_MEAN_IMAGE_HIGH  0x1fff
#define XNEURAL_NET_HLS_MACC_PERIPH_BUS_WIDTH_MEAN_IMAGE      32
#define XNEURAL_NET_HLS_MACC_PERIPH_BUS_DEPTH_MEAN_IMAGE      784
#define XNEURAL_NET_HLS_MACC_PERIPH_BUS_ADDR_INPUT_IMAGE_BASE 0x2000
#define XNEURAL_NET_HLS_MACC_PERIPH_BUS_ADDR_INPUT_IMAGE_HIGH 0x2fff
#define XNEURAL_NET_HLS_MACC_PERIPH_BUS_WIDTH_INPUT_IMAGE     32
#define XNEURAL_NET_HLS_MACC_PERIPH_BUS_DEPTH_INPUT_IMAGE     784

